# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class PyCoverageLcov(PythonPackage):
    """coverage-lcov is a simple CLI for converting .coverage files generated by Coverage.py to the LCOV format."""

    #homepage = "https://github.com/TheCleric/coverage-lcov"
    #url = "https://pypi.org/project/coverage-lcov/"
    pypi = "coverage-lcov/0.2.4.tar.gz"

    maintainers = ["rhoneyager-tomorrow"]

    version("0.2.4", sha256="d65a77e4694c5dab041b2ba9725d819de12d8f26efc93f47bcd3dc25a74f017c")

    depends_on("python", type=("build", "run"))
    depends_on("py-coverage", type=("build", "run"))
    depends_on("py-click", type=("build", "run"))
    depends_on("py-poetry")
    depends_on("py-toml", type=("build", "run"))

