compilers:
- compiler:
    spec: oneapi@=2024.2.1
    paths:
      cc: /opt/intel/oneapi/compiler/2024.2/bin/icx
      cxx: /opt/intel/oneapi/compiler/2024.2/bin/icpx
      f77: /opt/intel/oneapi/compiler/2024.2/bin/ifort
      fc: /opt/intel/oneapi/compiler/2024.2/bin/ifort
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules:
    - tbb/2021.13
    - compiler-rt/2024.2.1
    - compiler/2024.2.1
    - ifort/2024.2.1
    environment:
      prepend_path:
        PATH: '/usr/bin'
        LD_LIBRARY_PATH: '/usr/lib:/usr/lib64:/usr/lib/x86_64-linux-gnu'
        CPATH: '/usr/include/x86_64-linux-gnu/c++/12'
    extra_rpaths: []

- compiler:
    spec: gcc@12.3.0
    paths:
      cc: /usr/bin/gcc-12
      cxx: /usr/bin/g++-12
      f77: /usr/bin/gfortran-12
      fc: /usr/bin/gfortran-12
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
