compilers::
- compiler:
    spec: oneapi@=2024.2.1
    paths:
      cc: /stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/bin/icx
      cxx: /stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/bin/icpx
#      f77: /stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/bin/ifx
#      fc: /stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/bin/ifx
      f77: /stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/bin/ifort
      fc: /stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/bin/ifort
    flags: {}
    operating_system: rocky9
    target: x86_64
    modules:
    - oneapi/2024.2.1
    environment:
      prepend_path:
        #PATH: '/usr/bin'
        LD_LIBRARY_PATH: '/stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/linux/lib:/stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/linux/lib/x64:/stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/linux/lib/intel64_lin'
        #CPATH: '/usr/include'
    extra_rpaths:
    - /stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/linux/lib
    - /stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/linux/lib/x64
    - /stacks/compilers/spack-compilers-2024-08-28/envs/compilers/views/main/intel-oneapi-compilers-2024.2.1/compiler/2024.2/linux/lib/intel64_lin

- compiler:
    spec: gcc@=13.3.1
    paths:
      cc: /opt/rh/gcc-toolset-13/root/usr/bin/gcc
      cxx: /opt/rh/gcc-toolset-13/root/usr/bin/g++
      f77: /opt/rh/gcc-toolset-13/root/usr/bin/gfortran
      fc: /opt/rh/gcc-toolset-13/root/usr/bin/gfortran
    flags: {}
    operating_system: rocky9
    target: x86_64
    modules:
      - gcc/13.3.1
    environment:
      prepend_path:
        PATH: '/opt/rh/gcc-toolset-13/root/usr/bin'
        LD_LIBRARY_PATH: '/opt/rh/gcc-toolset-13/root/lib:/opt/rh/gcc-toolset-13/root/lib64'
    extra_rpaths:
    - /opt/rh/gcc-toolset-13/root/lib
    - /opt/rh/gcc-toolset-13/root/lib64

#- compiler:
#    spec: gcc@11.3.1
#    paths:
#      cc: /usr/bin/gcc
#      cxx: /usr/bin/g++
#      f77: /usr/bin/gfortran
#      fc: /usr/bin/gfortran
#    flags: {}
#    operating_system: rocky9
#    target: x86_64
#    modules: []
#    environment: {}
#    extra_rpaths: []

