spack:
  concretizer:
    unify: when_possible

  view: false
  include:
  - site
   - common

  definitions:
  - compilers: ['%oneapi']
  - packages:
    - tomorrow-skylab-env

  specs:
  - matrix:
    - [$packages]
    - [$compilers]
  packages:
    all:
      prefer: ['%oneapi']
