# Note that an upstream must be set for this template using
# spack create env --upstream=/path/to/envs/env-name/install
# Also, the compilers must be set manually below to match the
# compilers of the upstream environment

spack:
  concretizer:
    unify: when_possible

  view: false
  include:
  - site
  - common
  definitions:
  #- compilers: ['%gcc', '%intel', '%oneapi']
  - compilers: ['%intel']
  - packages:
    - tomorrow-base-env
    - tomorrow-wrf-env

  specs:
  - matrix:
    - [$packages]
    - [$compilers]
