# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *


class MpasModelJedi(CMakePackage):
    """The Model for Prediction Across Scales (MPAS) is a collaborative
    project for developing atmosphere, ocean and other earth-system
    simulation components for use in climate, regional climate and weather
    studies. JEDI version."""

    homepage = "https://mpas-dev.github.io/"
    git = 'https://github.com/JCSDA/MPAS-Model.git'

    maintainers = ["rhoneyager-tomorrow"]

    # options: double precision, gptl profiling, openmp, shared libs, cores to build
    variant(
        "cores",
        default="atmosphere",
        description="MPAS cores to build",
        multi=True,
        values=("atmosphere", "init_atmosphere", "landice",
                "ocean", "seaice", "sw", "test"),
    )
    variant('external-esmf', default=True, description='Use external esmf')
    #variant('gptl', default=False, description='Use GPTL profiling library (if available)')
    variant('openmp', default=True, description='Build with OpenMP support')
    variant(
        "precision",
        default="double",
        description="MPAS will be built with double/single precision reals.",
        values=("double", "single"),
        multi=False,
    )

    depends_on('git', type=('build'))
    depends_on('llvm-openmp', when='%apple-clang', type=('build', 'link', 'run'))
    depends_on('mpi')
    depends_on('netcdf-c')
    depends_on('netcdf-fortran')
    depends_on("parallelio+pnetcdf")
    # esmf is optional.a
    depends_on("esmf", when="+external-esmf")
    # gptl is optional

    version('7.0.jcsda3', commit='3ecd59e2cdeadf5e3a1d6a11aa14a4905e7f60a2')

    def cmake_args(self):
        spec = self.spec

        cmake_args = [
            self.define_from_variant('MPAS_OPENMP',  'openmp'),
            self.define_from_variant('MPAS_CORES', 'cores'),
        ]
        if spec.satisfies("precision=double"):
            cmake_args.append("-DMPAS_DOUBLE_PRECISION:BOOL=ON")
        else:
            cmake_args.append("-DMPAS_DOUBLE_PRECISION:BOOL=OFF")

        return cmake_args

    # Patches to v3:
    # 1) The module install include directory is slightly wrong.
    #
    # 2) In PackageConfig.cmake, there is a circular import dependency at lines 41 and 42:
    #     include("${CMAKE_CURRENT_LIST_DIR}/${_project_name_lower}-targets.cmake")
    #     include("${CMAKE_CURRENT_LIST_DIR}/${_project_name_lower}-targets-core.cmake")
    # These targets.cmake files are auto-generated by CMake, any they don't interact well
    # based on some of CMake's assumptions about target names.
    # The first targets.cmake uses file(GLOB CONFIG_FILES "${_DIR}/mpas-targets-*.cmake")
    # and this accidentally picks up files in targets-core.
    # To fix, we simply adjust the top-level CMakeLists.txt to
    # rename targets.cmake to targets-main.cmake.
    patch('v3.installs.patch', when='@7.0.jcsda3')

    # 3) Add external ESMF package searches.
    patch('external-esmf.patch', when='@7.0.jcsda3')

